#!/usr/bin/env python3
"""Emit the data contract a face design must respect, derived from the code.

Never hand-maintain the output of this script. A contract written by hand at a
layer boundary rots silently, and a design that consumed it goes on being
confidently wrong.

Usage:
    ./extract-contract.py [--radio ftx1] [--json]

Run from the repository root. Exits non-zero if a source file it needs is
missing or yields nothing, because an empty contract is indistinguishable from
a clean one and the second is never true.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import NoReturn

VIEW_MODEL = Path("frontend/src/semantic/radio-view-model.ts")
LAYOUT_CONTRACT = Path("frontend/src/presentation/layouts/contract.ts")


def die(msg: str) -> NoReturn:
    print(f"extract-contract: {msg}", file=sys.stderr)
    raise SystemExit(1)


def read(path: Path) -> str:
    if not path.is_file():
        die(f"missing {path} — run from the repository root")
    return path.read_text(encoding="utf-8")


def surfaces() -> list[str]:
    """The closed set of surfaces a layout may mount."""
    text = read(LAYOUT_CONTRACT)
    m = re.search(r"SEMANTIC_SURFACE_NAMES\s*=\s*\[(.*?)\]", text, re.S)
    if not m:
        die(f"SEMANTIC_SURFACE_NAMES not found in {LAYOUT_CONTRACT}")
    names = re.findall(r"'([A-Za-z]+)'", m.group(1))
    if not names:
        die("SEMANTIC_SURFACE_NAMES parsed to zero entries")
    return names


def unknown_reasons(text: str) -> list[str]:
    """Why a reading can be absent. This is the vocabulary designs collapse."""
    m = re.search(r"status:\s*'unknown';\s*reason:\s*([^}]+)", text)
    if not m:
        die("no `status:'unknown'; reason:` union found — the state model moved")
    reasons = re.findall(r"'([a-z-]+)'", m.group(1))
    if not reasons:
        die("unknown-reason union parsed to zero entries")
    return reasons


def view_models(text: str) -> dict[str, list[tuple[str, str]]]:
    """Every `*ViewModel` interface and its declared fields."""
    out: dict[str, list[tuple[str, str]]] = {}
    for block in re.finditer(
        r"export interface (\w+ViewModel)\s*\{(.*?)\n\}", text, re.S
    ):
        name, body = block.group(1), block.group(2)
        fields = [
            (f.group(1), f.group(2).strip())
            for f in re.finditer(r"^\s{2}(\w+)\??:\s*([^;]+);", body, re.M)
        ]
        out[name] = fields
    if not out:
        die("no *ViewModel interfaces parsed — the file shape moved")
    return out


def field_shapes(text: str) -> dict[str, str]:
    """The reading/availability pair shapes, by declared name."""
    out = {}
    # A type body may contain `;` inside braces, so stop at a `;` that ends a
    # line rather than at the first one. A truncated shape reads as a real one.
    for m in re.finditer(
        r"export type (\w*(?:Reading|Field)\w*)\s*(?:<[^>]*>)?\s*=\s*(.*?);\s*$",
        text, re.S | re.M,
    ):
        out[m.group(1)] = " ".join(m.group(2).split())
    for m in re.finditer(r"export interface (\w*Field)\s*\{(.*?)\n\}", text, re.S):
        members = re.findall(r"^\s{2}(\w+):", m.group(2), re.M)
        out[m.group(1)] = "{ " + ", ".join(members) + " }"
    return out


def radio_declares(radio: str) -> tuple[list[str], str]:
    """What this particular radio's profile declares. A field in the view model
    does not mean this radio reports it."""
    path = Path("rigs") / f"{radio}.toml"
    if not path.is_file():
        available = sorted(p.stem for p in Path("rigs").glob("*.toml"))
        die(f"no profile {path}; available: {', '.join(available)}")
    text = path.read_text(encoding="utf-8")
    feats: list[str] = []
    m = re.search(r"^features\s*=\s*\[(.*?)\]", text, re.S | re.M)
    if m:
        feats = re.findall(r'"([^"]+)"', m.group(1))
    return feats, str(path)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--radio", default="ftx1")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args()

    vm_text = read(VIEW_MODEL)
    data = {
        "surfaces": surfaces(),
        "unknownReasons": unknown_reasons(vm_text),
        "viewModels": {k: dict(v) for k, v in view_models(vm_text).items()},
        "fieldShapes": field_shapes(vm_text),
        "radio": args.radio,
        "radioFeatures": radio_declares(args.radio)[0],
        "sources": [str(VIEW_MODEL), str(LAYOUT_CONTRACT), radio_declares(args.radio)[1]],
    }

    if args.json:
        print(json.dumps(data, indent=2))
        return

    print("# Data contract for a face design\n")
    print("Generated by `.claude/skills/design-a-face/extract-contract.py`.")
    print("Do not edit; re-run it.\n")
    print("Sources read: " + ", ".join(f"`{s}`" for s in data["sources"]) + "\n")

    print(f"## Surfaces a layout may mount ({len(data['surfaces'])})\n")
    print(", ".join(f"`{s}`" for s in data["surfaces"]) + "\n")

    print("## Why a reading can be absent\n")
    print("A reading is `known` with a value, or `unknown` with one of these "
          "reasons. They are not shades of the same thing — *unsupported* and "
          "*stale* mean opposite things to an operator.\n")
    for r in data["unknownReasons"]:
        print(f"- `{r}`")
    print()

    print("## Field shapes\n")
    for name, shape in sorted(data["fieldShapes"].items()):
        print(f"- `{name}` = {shape}")
    print()

    print("## Per surface\n")
    for name, fields in sorted(data["viewModels"].items()):
        print(f"### `{name}` ({len(fields)} fields)\n")
        for fname, ftype in fields.items():
            print(f"- `{fname}`: `{ftype}`")
        print()

    feats = data["radioFeatures"]
    print(f"## What `{args.radio}` declares ({len(feats)} features)\n")
    print("A field in the view model does not mean this radio reports it.\n")
    print(", ".join(f"`{f}`" for f in feats) if feats else "_none parsed_")
    print()


if __name__ == "__main__":
    main()
