export type ManagedTransmitIntent = { kind: 'rx' } | { kind: 'transmit' } | { kind: 'ptt'; owner: string };
export type ManagedTransmitDocument = Readonly<{ schemaVersion: 1; sampledAt: string; managedTransmit: { status: 'available'; intent: ManagedTransmitIntent; releaseRequired: boolean; lastError: string | null; lastActuation: { operation: 'ptt_on' | 'transmit_on' | 'force_receive'; result: 'accepted' | 'rejected' | 'uncertain'; attemptId: string } | null; abortErrors: readonly { operation: 'stop_cw' | 'stop_tune'; error: string }[]; tot: { configuredSeconds: number | null; active: boolean; remainingMs: number | null; expiresAt: string | null } } | { status: 'unavailable'; reason: 'authority_not_composed' }; txObservation: { observedPtt: 'on' | 'off' | 'unknown' } }>;

const record = (value: unknown, path: string): Record<string, unknown> => { if (!value || typeof value !== 'object' || Array.isArray(value)) throw new TypeError(`Invalid managed transmit payload at ${path}`); return value as Record<string, unknown>; };
const exact = (value: Record<string, unknown>, keys: readonly string[], path: string) => { if (Object.keys(value).some((key) => !keys.includes(key)) || keys.some((key) => !(key in value))) throw new TypeError(`Invalid managed transmit payload at ${path}`); };
const string = (v: unknown, p: string) => { if (typeof v !== 'string') throw new TypeError(`Invalid managed transmit payload at ${p}`); return v; };
const finite = (v: unknown, p: string) => { if (typeof v !== 'number' || !Number.isFinite(v)) throw new TypeError(`Invalid managed transmit payload at ${p}`); return v; };

export function validateManagedTransmitDocument(value: unknown): ManagedTransmitDocument {
  const root = record(value, '$'); exact(root, ['schemaVersion', 'sampledAt', 'managedTransmit', 'txObservation'], '$'); if (root.schemaVersion !== 1) throw new TypeError('Invalid managed transmit payload at $.schemaVersion'); string(root.sampledAt, '$.sampledAt');
  const observation = record(root.txObservation, '$.txObservation'); exact(observation, ['observedPtt'], '$.txObservation'); if (!['on', 'off', 'unknown'].includes(string(observation.observedPtt, '$.txObservation.observedPtt'))) throw new TypeError('Invalid managed transmit payload at $.txObservation.observedPtt');
  const managed = record(root.managedTransmit, '$.managedTransmit');
  if (managed.status === 'unavailable') { exact(managed, ['status', 'reason'], '$.managedTransmit'); if (managed.reason !== 'authority_not_composed') throw new TypeError('Invalid managed transmit payload at $.managedTransmit.reason'); return value as ManagedTransmitDocument; }
  exact(managed, ['status', 'intent', 'releaseRequired', 'lastError', 'lastActuation', 'abortErrors', 'tot'], '$.managedTransmit'); if (managed.status !== 'available' || typeof managed.releaseRequired !== 'boolean' || !(managed.lastError === null || typeof managed.lastError === 'string')) throw new TypeError('Invalid managed transmit payload at $.managedTransmit');
  const intent = record(managed.intent, '$.managedTransmit.intent'); if (intent.kind === 'ptt') { exact(intent, ['kind', 'owner'], '$.managedTransmit.intent'); if (!string(intent.owner, '$.managedTransmit.intent.owner')) throw new TypeError('Invalid managed transmit payload at $.managedTransmit.intent.owner'); } else { exact(intent, ['kind'], '$.managedTransmit.intent'); if (!['rx', 'transmit'].includes(string(intent.kind, '$.managedTransmit.intent.kind'))) throw new TypeError('Invalid managed transmit payload at $.managedTransmit.intent.kind'); }
  const tot = record(managed.tot, '$.managedTransmit.tot'); exact(tot, ['configuredSeconds', 'active', 'remainingMs', 'expiresAt'], '$.managedTransmit.tot'); if (typeof tot.active !== 'boolean' || !(tot.configuredSeconds === null || finite(tot.configuredSeconds, '$.managedTransmit.tot.configuredSeconds') > 0) || !(tot.remainingMs === null || (Number.isInteger(tot.remainingMs) && finite(tot.remainingMs, '$.managedTransmit.tot.remainingMs') >= 0)) || !(tot.expiresAt === null || typeof tot.expiresAt === 'string')) throw new TypeError('Invalid managed transmit payload at $.managedTransmit.tot'); if (tot.active !== (tot.remainingMs !== null)) throw new TypeError('Invalid managed transmit payload at $.managedTransmit.tot.active');
  return value as ManagedTransmitDocument;
}
