/**
 * field-status resolver tests (MOR-429).
 *
 * Covers parent/child availability resolution and — crucially — anchors the
 * frontend public-path keys to a REAL backend-emitted `field_status` payload.
 * The golden fixture `fixtures/empty-store-field-status.json` is generated by
 * `tests/test_field_status_frontend_fixture.py` from the backend public-state
 * projection of an empty StateStore; importing it here proves the keys the
 * toolbar/LCD gate on (`scopeControls.mode`, `main.agc`, …) actually match the
 * keys the backend emits and resolve to unavailable.
 */
import { describe, it, expect } from 'vitest';
import type { ServerState } from '$lib/types/state';
import {
  getFieldAvailability,
  isFieldAvailable,
  areFieldsAvailable,
} from '../field-status';
import emptyStoreFieldStatus from './fixtures/empty-store-field-status.json';

function stateWith(fieldStatus: Record<string, unknown>): ServerState {
  return { fieldStatus } as unknown as ServerState;
}

describe('field-status parent/child resolution', () => {
  it('treats a leaf as available when no entry and no ancestor entry exist', () => {
    const state = stateWith({
      'main.freqHz': { availability: 'available', freshness: 'fresh', observed: true },
    });
    expect(getFieldAvailability(state, 'scopeControls.mode')).toBe('available');
  });

  it('inherits a missing parent when the child has no own entry', () => {
    const state = stateWith({
      scopeControls: { availability: 'missing', freshness: 'unknown', observed: false },
    });
    expect(getFieldAvailability(state, 'scopeControls.mode')).toBe('missing');
    expect(isFieldAvailable(state, 'scopeControls.span')).toBe(false);
  });

  it('inherits a stale parent when the child has no own entry', () => {
    const state = stateWith({
      scopeControls: { availability: 'stale', freshness: 'stale', observed: true },
    });
    expect(getFieldAvailability(state, 'scopeControls.refDb')).toBe('stale');
  });

  it('lets a missing/stale parent override a child that claims available', () => {
    const state = stateWith({
      scopeControls: { availability: 'missing', freshness: 'unknown', observed: false },
      'scopeControls.span': { availability: 'available', freshness: 'fresh', observed: true },
    });
    // The group is unobserved as a whole — one stale-by-inheritance leaf must
    // not be confirmed even if it carries an `available` own entry.
    expect(getFieldAvailability(state, 'scopeControls.span')).toBe('missing');
  });

  it('keeps an own stale entry unavailable regardless of parent', () => {
    const state = stateWith({
      'scopeControls.span': { availability: 'stale', freshness: 'stale', observed: true },
    });
    expect(getFieldAvailability(state, 'scopeControls.span')).toBe('stale');
    expect(isFieldAvailable(state, 'scopeControls.span')).toBe(false);
  });
});

describe('field-status anchored to the real backend payload', () => {
  const state = stateWith(emptyStoreFieldStatus as Record<string, unknown>);

  const toolbarScopeKeys = [
    'scopeControls.mode',
    'scopeControls.edge',
    'scopeControls.span',
    'scopeControls.speed',
    'scopeControls.hold',
    'scopeControls.refDb',
    'scopeControls.dual',
    'scopeControls.receiver',
  ];

  const backendKeys = Object.keys(emptyStoreFieldStatus as Record<string, unknown>);

  it('emits the scope-control leaves the toolbar gates on', () => {
    for (const key of toolbarScopeKeys) {
      expect(backendKeys, `backend must emit ${key}`).toContain(key);
    }
  });

  it('resolves every scope-control leaf to unavailable for an empty store', () => {
    expect(areFieldsAvailable(state, toolbarScopeKeys)).toBe(false);
    for (const key of toolbarScopeKeys) {
      expect(isFieldAvailable(state, key), `${key} should be unavailable`).toBe(false);
    }
  });

  it('resolves per-receiver LCD indicators (agc/preamp/att/…) to unavailable', () => {
    for (const key of ['main.agc', 'main.preamp', 'main.att', 'main.nb', 'main.nr', 'main.rfGain', 'main.squelch']) {
      expect(backendKeys, `backend must emit ${key}`).toContain(key);
      expect(isFieldAvailable(state, key), `${key} should be unavailable`).toBe(false);
    }
  });
});
