# ruff: noqa: F401  — all imports are intentional re-exports
"""CI-V command encoding and decoding for Icom transceivers.

CI-V frame format::

    FE FE <to> <from> <cmd> [<sub>] [<data>...] FD

For dual-receiver radios (IC-7610), commands marked Command29=true use::

    FE FE <to> <from> 29 <receiver> <cmd> [<sub>] [<data>...] FD

where ``receiver`` = ``0x00`` (MAIN) or ``0x01`` (SUB).

Reference: wfview icomcommander.cpp, IC-7610.rig
"""

# Re-export everything from sub-modules -- no logic in this file.

from ..types import bcd_decode

# --- _frame.py (kernel) ---
from ._frame import (
    CONTROLLER_ADDR,
    RECEIVER_MAIN,
    RECEIVER_SUB,
    _CMD_ACK,
    _CMD_FREQ_GET,
    _CMD_FREQ_SET,
    _CMD_LEVEL,
    _CMD_METER,
    _CMD_MODE_GET,
    _CMD_MODE_SET,
    _CMD_PREAMP,
    _CMD_PTT,
    _CMD_SELECTED_FREQ,
    _CMD_SELECTED_MODE,
    _SUB_ALC_METER,
    _SUB_POWER_METER,
    _SUB_PTT,
    _SUB_RF_POWER,
    _SUB_S_METER,
    _SUB_SWR_METER,
    build_civ_frame,
    build_cmd29_frame,
    parse_ack_nak,
    parse_civ_frame,
)

# --- _codec.py ---
from ._codec import (
    _bcd_byte,
    _bcd_decode_value,
    _level_bcd_decode,
    _level_bcd_encode,
    bcd_encode_value,
    filter_hz_to_index,
    filter_index_to_hz,
    hz_to_table_index,
    table_index_to_hz,
)

# --- _builders.py ---
from ._builders import (
    parse_bool_response,
    parse_level_response,
)

# --- freq.py ---
from .freq import (
    get_freq,
    get_frequency,
    get_selected_freq,
    get_selected_mode,
    get_unselected_freq,
    get_unselected_mode,
    parse_frequency_response,
    parse_selected_freq_response,
    parse_selected_mode_response,
    set_freq,
    set_frequency,
)

# --- mode.py ---
from .mode import (
    get_agc_time_constant,
    get_data_mode,
    get_filter_shape,
    get_filter_width,
    get_main_sub_tracking,
    get_mode,
    get_ssb_tx_bandwidth,
    parse_data_mode_response,
    parse_mode_response,
    set_agc_time_constant,
    set_data_mode,
    set_filter_shape,
    set_filter_width,
    set_main_sub_tracking,
    set_mode,
    set_ssb_tx_bandwidth,
)

# --- levels.py ---
from .levels import (
    get_af_level,
    get_anti_vox_gain,
    get_apf_type_level,
    get_break_in_delay,
    get_compressor_level,
    get_cw_pitch,
    get_dash_ratio,
    get_digisel_shift,
    get_drive_gain,
    get_key_speed,
    get_mic_gain,
    get_monitor_gain,
    get_nb_depth,
    get_nb_level,
    get_nb_width,
    get_notch_filter,
    get_nr_level,
    get_pbt_inner,
    get_pbt_outer,
    get_ref_adjust,
    get_rf_gain,
    get_rf_power,
    get_squelch,
    get_vox_delay,
    get_vox_gain,
    set_af_level,
    set_anti_vox_gain,
    set_apf_type_level,
    set_break_in_delay,
    set_compressor_level,
    set_cw_pitch,
    set_dash_ratio,
    set_digisel_shift,
    set_drive_gain,
    set_key_speed,
    set_mic_gain,
    set_monitor_gain,
    set_nb_depth,
    set_nb_level,
    set_nb_width,
    set_notch_filter,
    set_nr_level,
    set_pbt_inner,
    set_pbt_outer,
    set_ref_adjust,
    set_rf_gain,
    set_rf_power,
    set_squelch,
    set_vox_delay,
    set_vox_gain,
)

# --- meters.py ---
from .meters import (
    get_alc,
    get_comp_meter,
    get_id_meter,
    get_overflow_status,
    get_power_meter,
    get_s_meter,
    get_s_meter_sql_status,
    get_swr,
    get_various_squelch,
    get_vd_meter,
    parse_meter_response,
)

# --- ptt.py ---
from .ptt import ptt_off, ptt_on

# --- vfo.py ---
from .vfo import (
    get_dual_watch,
    get_main_sub_band,
    get_quick_dual_watch,
    get_quick_split,
    get_split,
    get_tuning_step,
    get_vfo,
    quick_dual_watch,
    quick_split,
    scan_set_df_span,
    scan_set_resume,
    scan_start,
    scan_start_type,
    scan_stop,
    VALID_DF_SPANS,
    VALID_SCAN_RESUME,
    VALID_SCAN_TYPES,
    select_vfo,
    set_dual_watch,
    set_dual_watch_off,
    set_dual_watch_on,
    set_quick_dual_watch,
    set_quick_split,
    set_split,
    set_tuning_step,
    set_vfo,
    start_scan,
    stop_scan,
    vfo_a_equals_b,
    vfo_swap,
)

# --- dsp.py ---
from .dsp import (
    get_af_mute,
    get_agc,
    get_attenuator,
    get_audio_peak_filter,
    get_auto_notch,
    get_break_in,
    get_compressor,
    get_dial_lock,
    get_digisel,
    get_ip_plus,
    get_manual_notch,
    get_manual_notch_width,
    get_monitor,
    get_nb,
    get_nr,
    get_preamp,
    get_twin_peak_filter,
    get_vox,
    set_af_mute,
    set_agc,
    set_attenuator,
    set_attenuator_level,
    set_audio_peak_filter,
    set_auto_notch,
    set_break_in,
    set_compressor,
    set_dial_lock,
    set_digisel,
    set_ip_plus,
    set_manual_notch,
    set_manual_notch_width,
    set_monitor,
    set_nb,
    set_nr,
    set_preamp,
    set_twin_peak_filter,
    set_vox,
)

# --- scope.py ---
from .scope import (
    get_scope_center_type,
    get_scope_during_tx,
    get_scope_edge,
    get_scope_fixed_edge,
    get_scope_hold,
    get_scope_main_sub,
    get_scope_mode,
    get_scope_rbw,
    get_scope_ref,
    get_scope_single_dual,
    get_scope_span,
    get_scope_speed,
    get_scope_vbw,
    parse_scope_center_type_response,
    parse_scope_during_tx_response,
    parse_scope_edge_response,
    parse_scope_fixed_edge_response,
    parse_scope_hold_response,
    parse_scope_main_sub_response,
    parse_scope_mode_response,
    parse_scope_rbw_response,
    parse_scope_ref_response,
    parse_scope_single_dual_response,
    parse_scope_span_response,
    parse_scope_speed_response,
    parse_scope_vbw_response,
    scope_data_output,
    scope_data_output_off,
    scope_data_output_on,
    scope_main_sub,
    scope_off,
    scope_on,
    scope_set_center_type,
    scope_set_during_tx,
    scope_set_edge,
    scope_set_fixed_edge,
    scope_set_hold,
    scope_set_mode,
    scope_set_rbw,
    scope_set_ref,
    scope_set_span,
    scope_set_speed,
    scope_set_vbw,
    scope_single_dual,
)

# --- cw.py ---
from .cw import send_cw, stop_cw

# --- power.py ---
from .power import get_powerstat, parse_powerstat, power_off, power_on

# --- speech.py ---
from .speech import get_speech, speech

# --- system.py ---
from .system import (
    get_band_edge_freq,
    get_rit_frequency,
    get_rit_status,
    get_rit_tx_status,
    get_system_date,
    get_system_time,
    get_transceiver_id,
    get_tuner_status,
    get_tx_freq_monitor,
    get_utc_offset,
    get_xfc_status,
    parse_rit_frequency_response,
    parse_system_date_response,
    parse_system_time_response,
    parse_utc_offset_response,
    set_rit_frequency,
    set_rit_status,
    set_rit_tx_status,
    set_system_date,
    set_system_time,
    set_tuner_status,
    set_tx_freq_monitor,
    set_utc_offset,
    set_xfc_status,
)

# --- tone.py ---
from .tone import (  # type: ignore[attr-defined]  # _SUB_REPEATER_TONE/TSQL are private re-exports
    _decode_tone_freq,
    _encode_tone_freq,
    _SUB_REPEATER_TONE,
    _SUB_REPEATER_TSQL,
    get_repeater_tone,
    get_repeater_tsql,
    get_tone_freq,
    get_tsql_freq,
    parse_tone_freq_response,
    parse_tsql_freq_response,
    set_repeater_tone,
    set_repeater_tsql,
    set_tone_freq,
    set_tsql_freq,
)

# --- memory.py ---
from .memory import (
    build_band_stack_get,
    build_band_stack_set,
    build_memory_clear,
    build_memory_contents_get,
    build_memory_contents_set,
    build_memory_mode_get,
    build_memory_mode_set,
    build_memory_to_vfo,
    build_memory_write,
    get_bsr,
    parse_band_stack_response,
    parse_memory_contents_response,
    parse_memory_mode_response,
    set_bsr,
)

# --- antenna.py ---
from .antenna import (
    get_antenna,
    get_antenna_1,
    get_antenna_2,
    get_rx_antenna,
    get_rx_antenna_ant1,
    get_rx_antenna_ant2,
    set_antenna,
    set_antenna_1,
    set_antenna_2,
    set_rx_antenna,
    set_rx_antenna_ant1,
    set_rx_antenna_ant2,
)

# --- tx_band.py ---
from .tx_band import (
    get_tx_band_count,
    get_tx_band_edge,
    parse_tx_band_count_response,
    parse_tx_band_edge_response,
)

# --- config.py ---
from .config import (
    get_acc1_mod_level,
    get_civ_output_ant,
    get_civ_transceive,
    get_data1_mod_input,
    get_data2_mod_input,
    get_data3_mod_input,
    get_data_off_mod_input,
    get_lan_mod_level,
    get_usb_mod_level,
    set_acc1_mod_level,
    set_civ_output_ant,
    set_civ_transceive,
    set_data1_mod_input,
    set_data2_mod_input,
    set_data3_mod_input,
    set_data_off_mod_input,
    set_lan_mod_level,
    set_usb_mod_level,
)

__all__ = [
    # Internal helpers re-exported for sibling modules
    "_bcd_byte",
    "_bcd_decode_value",
    "_level_bcd_decode",
    "_level_bcd_encode",
    "_decode_tone_freq",
    "_encode_tone_freq",
    "_SUB_REPEATER_TONE",
    "_SUB_REPEATER_TSQL",
    "_CMD_ACK",
    "_CMD_FREQ_GET",
    "_CMD_FREQ_SET",
    "_CMD_LEVEL",
    "_CMD_METER",
    "_CMD_MODE_GET",
    "_CMD_MODE_SET",
    "_CMD_PREAMP",
    "_CMD_PTT",
    "_CMD_SELECTED_FREQ",
    "_CMD_SELECTED_MODE",
    "_SUB_ALC_METER",
    "_SUB_POWER_METER",
    "_SUB_PTT",
    "_SUB_RF_POWER",
    "_SUB_S_METER",
    "_SUB_SWR_METER",
    # Public symbols
    "CONTROLLER_ADDR",
    "RECEIVER_MAIN",
    "RECEIVER_SUB",
    "bcd_decode",
    "build_civ_frame",
    "build_cmd29_frame",
    "bcd_encode_value",
    "filter_hz_to_index",
    "filter_index_to_hz",
    "table_index_to_hz",
    "hz_to_table_index",
    "parse_civ_frame",
    # TOML canonical names (primary)
    "get_freq",
    "set_freq",
    # Backward-compat aliases
    "get_frequency",
    "set_frequency",
    "get_mode",
    "set_mode",
    # TOML canonical names
    "get_rf_power",
    "set_rf_power",
    "get_s_meter",
    "get_swr",
    "get_alc",
    "ptt_on",
    "ptt_off",
    "parse_frequency_response",
    "parse_mode_response",
    "parse_meter_response",
    "parse_ack_nak",
    "send_cw",
    "stop_cw",
    "power_on",
    "power_off",
    "get_attenuator",
    "set_attenuator",
    "set_attenuator_level",
    "get_preamp",
    "set_preamp",
    "get_digisel",
    "set_digisel",
    "get_apf_type_level",
    "set_apf_type_level",
    "get_nr_level",
    "set_nr_level",
    "get_pbt_inner",
    "set_pbt_inner",
    "get_pbt_outer",
    "set_pbt_outer",
    "get_cw_pitch",
    "set_cw_pitch",
    "get_mic_gain",
    "set_mic_gain",
    "get_key_speed",
    "set_key_speed",
    "get_notch_filter",
    "set_notch_filter",
    "get_compressor_level",
    "set_compressor_level",
    "get_break_in_delay",
    "set_break_in_delay",
    "get_nb_level",
    "set_nb_level",
    "get_digisel_shift",
    "set_digisel_shift",
    "get_drive_gain",
    "set_drive_gain",
    "get_monitor_gain",
    "set_monitor_gain",
    "get_vox_gain",
    "set_vox_gain",
    "get_anti_vox_gain",
    "set_anti_vox_gain",
    "get_ref_adjust",
    "set_ref_adjust",
    "get_dash_ratio",
    "set_dash_ratio",
    "get_nb_depth",
    "set_nb_depth",
    "get_nb_width",
    "set_nb_width",
    "get_vox_delay",
    "set_vox_delay",
    "get_af_mute",
    "set_af_mute",
    # Squelch (TOML canonical)
    "get_squelch",
    "set_squelch",
    "get_s_meter_sql_status",
    "get_overflow_status",
    "get_agc",
    "set_agc",
    "get_audio_peak_filter",
    "set_audio_peak_filter",
    "get_auto_notch",
    "set_auto_notch",
    "get_compressor",
    "set_compressor",
    "get_monitor",
    "set_monitor",
    "get_vox",
    "set_vox",
    "get_break_in",
    "set_break_in",
    "get_manual_notch",
    "set_manual_notch",
    # Manual notch width (TOML canonical)
    "get_manual_notch_width",
    "set_manual_notch_width",
    "get_twin_peak_filter",
    "set_twin_peak_filter",
    "get_dial_lock",
    "set_dial_lock",
    # Selected/unselected receiver freq & mode (0x25/0x26)
    "get_selected_freq",
    "get_unselected_freq",
    "parse_selected_freq_response",
    "get_selected_mode",
    "get_unselected_mode",
    "parse_selected_mode_response",
    "_CMD_SELECTED_FREQ",
    "_CMD_SELECTED_MODE",
    "get_filter_shape",
    "set_filter_shape",
    # Filter width (TOML canonical)
    "get_filter_width",
    "set_filter_width",
    "get_ssb_tx_bandwidth",
    "set_ssb_tx_bandwidth",
    "get_main_sub_tracking",
    "set_main_sub_tracking",
    "get_agc_time_constant",
    "set_agc_time_constant",
    "get_data_mode",
    "set_data_mode",
    "parse_data_mode_response",
    "parse_level_response",
    "parse_bool_response",
    "scope_on",
    "scope_off",
    "scope_data_output",
    "scope_data_output_on",
    "scope_data_output_off",
    "get_scope_main_sub",
    "scope_main_sub",
    "get_scope_single_dual",
    "scope_single_dual",
    "get_scope_mode",
    "scope_set_mode",
    "get_scope_span",
    "scope_set_span",
    "get_scope_ref",
    "scope_set_ref",
    "get_scope_speed",
    "scope_set_speed",
    "get_scope_edge",
    "scope_set_edge",
    "get_scope_hold",
    "scope_set_hold",
    "get_scope_during_tx",
    "scope_set_during_tx",
    "get_scope_center_type",
    "scope_set_center_type",
    "get_scope_vbw",
    "scope_set_vbw",
    "get_scope_fixed_edge",
    "scope_set_fixed_edge",
    "get_scope_rbw",
    "scope_set_rbw",
    "parse_scope_main_sub_response",
    "parse_scope_single_dual_response",
    "parse_scope_mode_response",
    "parse_scope_span_response",
    "parse_scope_ref_response",
    "parse_scope_speed_response",
    "parse_scope_edge_response",
    "parse_scope_hold_response",
    "parse_scope_during_tx_response",
    "parse_scope_center_type_response",
    "parse_scope_vbw_response",
    "parse_scope_fixed_edge_response",
    "parse_scope_rbw_response",
    # Transceiver status family (#136)
    "get_band_edge_freq",
    "get_various_squelch",
    "get_power_meter",
    "get_comp_meter",
    "get_vd_meter",
    "get_id_meter",
    "get_tuner_status",
    "set_tuner_status",
    "get_tx_freq_monitor",
    "set_tx_freq_monitor",
    "get_rit_frequency",
    "set_rit_frequency",
    "get_rit_status",
    "set_rit_status",
    "get_rit_tx_status",
    "set_rit_tx_status",
    "parse_rit_frequency_response",
    # VFO (TOML canonical)
    "get_vfo",
    "set_vfo",
    "get_main_sub_band",
    # Backward-compat aliases
    "select_vfo",
    # VFO / Dual Watch / Scanning (#132)
    "get_tuning_step",
    "set_tuning_step",
    # Scanning (TOML canonical)
    "scan_start",
    "scan_start_type",
    "scan_stop",
    "scan_set_df_span",
    "scan_set_resume",
    "VALID_SCAN_TYPES",
    "VALID_DF_SPANS",
    "VALID_SCAN_RESUME",
    # Backward-compat aliases
    "start_scan",
    "stop_scan",
    "set_dual_watch_off",
    "set_dual_watch_on",
    "get_dual_watch",
    "set_dual_watch",
    "quick_dual_watch",
    "quick_split",
    # Quick commands (TOML canonical)
    "get_quick_dual_watch",
    "set_quick_dual_watch",
    "get_quick_split",
    "set_quick_split",
    # Speech (TOML canonical)
    "get_speech",
    # Backward-compat alias
    "speech",
    # Tone/TSQL (#134)
    "get_repeater_tone",
    "set_repeater_tone",
    "get_repeater_tsql",
    "set_repeater_tsql",
    "get_tone_freq",
    "set_tone_freq",
    "get_tsql_freq",
    "set_tsql_freq",
    "parse_tone_freq_response",
    "parse_tsql_freq_response",
    # System/Config commands (#135)
    "get_antenna_1",
    "set_antenna_1",
    "get_antenna_2",
    "set_antenna_2",
    "get_rx_antenna_ant1",
    "set_rx_antenna_ant1",
    "get_rx_antenna_ant2",
    "set_rx_antenna_ant2",
    # Antenna aliases (TOML canonical)
    "get_antenna",
    "set_antenna",
    "get_rx_antenna",
    "set_rx_antenna",
    "get_acc1_mod_level",
    "set_acc1_mod_level",
    "get_usb_mod_level",
    "set_usb_mod_level",
    "get_lan_mod_level",
    "set_lan_mod_level",
    "get_data_off_mod_input",
    "set_data_off_mod_input",
    "get_data1_mod_input",
    "set_data1_mod_input",
    "get_data2_mod_input",
    "set_data2_mod_input",
    "get_data3_mod_input",
    "set_data3_mod_input",
    "get_civ_transceive",
    "set_civ_transceive",
    "get_civ_output_ant",
    "set_civ_output_ant",
    "get_system_date",
    "set_system_date",
    "parse_system_date_response",
    "get_system_time",
    "set_system_time",
    "parse_system_time_response",
    "get_utc_offset",
    "set_utc_offset",
    "parse_utc_offset_response",
    # Band stacking (TOML canonical)
    "get_bsr",
    "set_bsr",
    # Backward-compat aliases
    "build_band_stack_get",
    "build_band_stack_set",
    # Power/status
    "get_powerstat",
    "parse_powerstat",
    "get_transceiver_id",
    "get_xfc_status",
    "set_xfc_status",
    # VFO extras
    "vfo_a_equals_b",
    "vfo_swap",
    "get_split",
    "set_split",
    # Memory
    "build_memory_clear",
    "build_memory_contents_get",
    "build_memory_contents_set",
    "build_memory_mode_get",
    "build_memory_mode_set",
    "build_memory_to_vfo",
    "build_memory_write",
    "parse_memory_mode_response",
    "parse_memory_contents_response",
    "parse_band_stack_response",
    # Levels extras
    "get_af_level",
    "set_af_level",
    "get_rf_gain",
    "set_rf_gain",
    "get_ip_plus",
    "set_ip_plus",
    "get_nb",
    "set_nb",
    "get_nr",
    "set_nr",
    # TX band edge (0x1E)
    "get_tx_band_count",
    "get_tx_band_edge",
    "parse_tx_band_count_response",
    "parse_tx_band_edge_response",
]
